api_docs:
  href: https://scalenowai.com/use-cases/
  label: :label_api_doc
api:
  authentication_basic_auth:
    href: "#"
blog:
  href: https://scalenowai.com/post/
  label: homescreen.links.blog
blog_article_progress_changes:
  href: "#"
  label: Significant changes to progress and work estimates
chargebee:
  href: "#"
client_credentials_code_flow:
  href: "#"
  label: oauth.flows.client_credentials
configuration_guide:
  href: "#"
  label: links.configuration_guide
contact:
  href: "#"
  label: links.get_in_touch
contact_us:
  href: "#"
crowdin:
  href: https://scalenow.com.au/casestudies.html
  label: :label_add_edit_translations
data_privacy:
  href: https://scalenowai.com/australian-privacy-principles-apps/
  label: :label_privacy_policy
date_format_settings_documentation:
  href: "#"
digital_accessibility:
  href: https://scalenowai.com/aiservice/
  label: :label_digital_accessibility
disable_password_login:
  href: "#"
docker_installation:
  href: "#"
  label: Docker installation
enterprise_features:
  attribute_highlighting:
    href: "#"
  board_view:
    href: "#"
  boards:
    href: "#"
  conditional_highlighting:
    href: "#"
  custom_field_hierarchies:
    href: "#"
  custom_field_multiselect:
    href: "#"
  custom_field_projects:
    href: "#"
  customize_life_cycle:
    href: "#"
  default:
    href: "#"
  feature_comparison:
    href: "#"
  form_configuration:
    href: "#"
  internal_comments:
    href: "#"
  nextcloud_sso:
    href: "#"
  readonly_work_packages:
    href: "#"
  work_package_subject_generation:
    href: "#"
enterprise_support:
  href: https://scalenowai.com/support/
  label: :label_enterprise_support
enterprise_support_as_community:
  href: https://scalenowai.com/support/
  label: :label_enterprise_support
enterprise_welcome_video:
  href: "#"
forums:
  href: https://scalenowai.com/scaled-agile-framework/
  label: homescreen.links.forums
get_started_videos:
  href: "#"
glossary:
  href: https://scalenowai.com/glossary/
  label: homescreen.links.glossary
github:
  href: "#"
ical_docs:
  href: "#"
installation_guides:
  href: "#"
  label: :label_installation_guides
integrations:
  href: "#"
ldap_encryption_documentation:
  href: "#"
manual_installation:
  href: "#"
  label: Manual installation
newsletter:
  href: https://scalenowai.com/
  label: homescreen.links.newsletter
security_alerts:
  href: "#"
  label: homescreen.links.security_alerts
oauth_authorization_code_flow:
  href: "#"
  label: oauth.flows.authorization_code
onboarding_video_url:
  href: "#"
  label: top_menu.getting_started
openproject_docs:
  href: "#"
origin_mdn_documentation:
  href: "#"
packager_installation:
  href: "#"
  label: Packaged installation
postgres_13_upgrade:
  href: "#"
postgres_17_upgrade:
  href: "#"
postgres_migration:
  href: "#"
  label: :homescreen.links.postgres_migration
pricing:
  href: "#"
progress_tracking_docs:
  href: "#"
release_notes:
  href: https://scalenowai.com/termsofservice/
  label: :label_release_notes
release_notes_14_0_1:
  href: "#"
  label: Release notes for OpenProject 14.0.1
report_bug:
  href: https://github.com/scalenow/scalenow-AI/issues
  label: :label_report_bug
roadmap:
  href: https://scalenowai.com/
  label: :label_development_roadmap
security_badge_documentation:
  href: "#"
shortcuts:
  href: "#"
  label: homescreen.links.shortcuts
storage_docs:
  health_status:
    href: "#"
  nextcloud_oauth_application:
    href: "#"
  nextcloud_setup:
    href: "#"
  nextcloud_sso:
    href: "#"
  one_drive_drive_id_guide:
    href: "#"
  one_drive_oauth_application:
    href: "#"
  one_drive_setup:
    href: "#"
  sharepoint_drive_id_guide:
    href: "#"
  sharepoint_oauth_application:
    href: "#"
  sharepoint_setup:
    href: "#"
  troubleshooting:
    href: "#"
sysadmin_docs:
  ldap:
    href: "#"
  oidc:
    href: "#"
  oidc_acr_values:
    href: "#"
  oidc_claims:
    href: "#"
  oidc_groups:
    href: "#"
  saml:
    href: "#"
  scim:
    href: "#"
  scim_authentication:
    href: "#"
  scim_jwt_authetication_method:
    href: "#"
text_formatting:
  href: "#"
  label: :setting_text_formatting
upgrade_guides:
  href: "#"
  label: :label_upgrade_guides
upsell:
  href: "#"
  label: homescreen.links.upgrade_enterprise_edition
upsell_benefits_features:
  href: "#"
  label: noscript_learn_more
upsell_benefits_installation:
  href: "#"
  label: noscript_learn_more
upsell_benefits_security:
  href: "#"
  label: noscript_learn_more
upsell_benefits_support:
  href: "#"
  label: noscript_learn_more
upsell_get_quote:
  href: "#"
  label: admin.enterprise.get_quote
user_guides:
  href: https://scalenowai.com/user-guide-2/
  label: homescreen.links.user_guides
user_guide:
  access_tokens:
    href: "#"
webinar_videos:
  href: "#"
website:
  href: https://www.scalenowai.com
  label: label_openproject_website
